namespace:
  create: false

llm:
  persistence:
    size: 20Gi
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi

api:
  replicaCount: 2
  logLevel: INFO
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

ui:
  replicaCount: 2
  service:
    type: ClusterIP
    nodePort: null
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

ingress:
  enabled: true
  host: genai.prod.local
