apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai-platform.componentName" (dict "root" . "component" "llm") }}
  namespace: {{ include "genai-platform.namespace" . }}
  labels:
    {{- include "genai-platform.labels" . | nindent 4 }}
    {{- include "genai-platform.componentLabels" (dict "root" . "component" "llm") | nindent 4 }}
spec:
  type: {{ .Values.llm.service.type }}
  selector:
    {{- include "genai-platform.componentLabels" (dict "root" . "component" "llm") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.llm.service.port }}
      targetPort: http
