apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: genai-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arjunachari12/genai-k8s.git
    path: genai-platform/helm/genai-platform
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-staging.yaml
      values: |
        ui:
          service:
            type: ClusterIP
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: genai-gitops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
